#!/usr/bin/env python3
"""
AICL White Paper Generator v0.4
Architecture Compilation with Explicable Compilation

Generates a comprehensive white paper centered on the thesis that
a compiler which cannot explain why it generated a line of code
should not generate it.
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm, inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, HRFlowable, ListFlowable, ListItem,
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: cold | Mode: minimal | Harmony: split_complementary
# Contrast: text:bg=15.93 | accent:bg=4.86
ACCENT       = colors.HexColor('#b24c2a')
TEXT_PRIMARY  = colors.HexColor('#1b1a18')
TEXT_MUTED    = colors.HexColor('#848077')
BG_SURFACE   = colors.HexColor('#e9e6e1')
BG_PAGE      = colors.HexColor('#f5f5f3')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Page Setup ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 22 * mm
RIGHT_MARGIN = 22 * mm
TOP_MARGIN = 25 * mm
BOTTOM_MARGIN = 25 * mm
CONTENT_W = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Register Fonts ━━
_font_dir = '/usr/share/fonts/truetype'
pdfmetrics.registerFont(TTFont('DejaVuSerif', f'{_font_dir}/dejavu/DejaVuSerif.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSerifBold', f'{_font_dir}/dejavu/DejaVuSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Carlito', f'{_font_dir}/english/Carlito-Regular.ttf'))
pdfmetrics.registerFont(TTFont('CarlitoBold', f'{_font_dir}/english/Carlito-Bold.ttf'))
pdfmetrics.registerFont(TTFont('CarlitoItalic', f'{_font_dir}/english/Carlito-Italic.ttf'))
pdfmetrics.registerFont(TTFont('CarlitoBoldItalic', f'{_font_dir}/english/Carlito-BoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{_font_dir}/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSansBold', f'{_font_dir}/dejavu/DejaVuSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSansMono', f'{_font_dir}/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('DejaVuSerif', normal='DejaVuSerif', bold='DejaVuSerifBold')
registerFontFamily('Carlito', normal='Carlito', bold='CarlitoBold', italic='CarlitoItalic', boldItalic='CarlitoBoldItalic')

# ━━ Styles ━━
styles = getSampleStyleSheet()

cover_title_style = ParagraphStyle(
    'CoverTitle', parent=styles['Title'],
    fontName='DejaVuSerif', fontSize=34, leading=40,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceAfter=6*mm,
)
cover_subtitle_style = ParagraphStyle(
    'CoverSubtitle', parent=styles['Title'],
    fontName='Carlito', fontSize=15, leading=20,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceAfter=4*mm,
)
cover_meta_style = ParagraphStyle(
    'CoverMeta', parent=styles['Normal'],
    fontName='Carlito', fontSize=10.5, leading=15,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
)

h1_style = ParagraphStyle(
    'H1', parent=styles['Heading1'],
    fontName='DejaVuSerif', fontSize=22, leading=28,
    textColor=TEXT_PRIMARY, spaceBefore=14*mm, spaceAfter=6*mm,
    borderColor=ACCENT, borderWidth=0, borderPadding=0,
)
h2_style = ParagraphStyle(
    'H2', parent=styles['Heading2'],
    fontName='DejaVuSerif', fontSize=16, leading=22,
    textColor=ACCENT, spaceBefore=8*mm, spaceAfter=4*mm,
)
h3_style = ParagraphStyle(
    'H3', parent=styles['Heading3'],
    fontName='CarlitoBold', fontSize=12.5, leading=17,
    textColor=TEXT_PRIMARY, spaceBefore=5*mm, spaceAfter=3*mm,
)
body_style = ParagraphStyle(
    'Body', parent=styles['Normal'],
    fontName='Carlito', fontSize=10, leading=15,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY,
    spaceBefore=1.5*mm, spaceAfter=3*mm,
    firstLineIndent=0,
)
body_indent_style = ParagraphStyle(
    'BodyIndent', parent=body_style,
    leftIndent=8*mm,
)
quote_style = ParagraphStyle(
    'Quote', parent=body_style,
    fontName='CarlitoItalic', fontSize=10.5, leading=16,
    leftIndent=12*mm, rightIndent=12*mm,
    textColor=ACCENT, spaceBefore=4*mm, spaceAfter=4*mm,
    alignment=TA_LEFT,
)
code_style = ParagraphStyle(
    'Code', parent=styles['Code'],
    fontName='DejaVuSansMono', fontSize=8.5, leading=12,
    textColor=TEXT_PRIMARY,
    backColor=BG_SURFACE,
    leftIndent=6*mm, rightIndent=6*mm,
    spaceBefore=3*mm, spaceAfter=3*mm,
    borderWidth=0,
)
caption_style = ParagraphStyle(
    'Caption', parent=styles['Normal'],
    fontName='CarlitoItalic', fontSize=9, leading=13,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
    spaceBefore=2*mm, spaceAfter=4*mm,
)
toc_h1_style = ParagraphStyle(
    'TOC1', parent=styles['Normal'],
    fontName='CarlitoBold', fontSize=11, leading=18,
    textColor=TEXT_PRIMARY, leftIndent=0,
)
toc_h2_style = ParagraphStyle(
    'TOC2', parent=styles['Normal'],
    fontName='Carlito', fontSize=10, leading=16,
    textColor=TEXT_MUTED, leftIndent=10*mm,
)
footnote_style = ParagraphStyle(
    'Footnote', parent=styles['Normal'],
    fontName='Carlito', fontSize=8, leading=11,
    textColor=TEXT_MUTED, alignment=TA_LEFT,
)

# ━━ Helper Functions ━━
def make_table(headers, rows, col_widths=None):
    """Create a styled table."""
    data = [headers] + rows
    if col_widths is None:
        n = len(headers)
        col_widths = [CONTENT_W / n] * n
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('FONTNAME', (0, 0), (-1, 0), 'CarlitoBold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9.5),
        ('FONTNAME', (0, 1), (-1, -1), 'Carlito'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('LEADING', (0, 0), (-1, -1), 13),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#cccccc')),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    return t

def hr():
    """Horizontal rule."""
    return HRFlowable(width="100%", thickness=0.5, color=ACCENT, spaceBefore=3*mm, spaceAfter=3*mm)

def p(text, style=None):
    """Paragraph shorthand."""
    return Paragraph(text, style or body_style)

def code(text):
    """Code block."""
    return Paragraph(text.replace('\n', '<br/>'), code_style)

def quote(text):
    """Quote block."""
    return Paragraph(text, quote_style)

# ━━ Page Templates ━━
def page_header_footer(canvas, doc):
    """Add page numbers and subtle header."""
    canvas.saveState()
    canvas.setFont('Carlito', 8)
    canvas.setFillColor(TEXT_MUTED)
    # Footer
    canvas.drawCentredString(PAGE_W / 2, 14 * mm, f"{doc.page}")
    # Header line
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(0.3)
    canvas.line(LEFT_MARGIN, PAGE_H - 18*mm, PAGE_W - RIGHT_MARGIN, PAGE_H - 18*mm)
    # Header text
    canvas.setFont('Carlito', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_MARGIN, PAGE_H - 17*mm, "AICL - Architecture Compilation Language")
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, PAGE_H - 17*mm, "v0.4.0 White Paper")
    canvas.restoreState()

def cover_page_template(canvas, doc):
    """Cover page - no header/footer."""
    pass

# ━━ Build Document ━━
def build_whitepaper():
    output_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                               'docs', 'whitepaper.pdf')

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title='AICL: Architecture Compilation with Explicable Compilation',
        author='Philippe-Antoine',
        subject='AICL White Paper v0.4',
    )

    story = []

    # ════════════════════════════════════════════
    # COVER PAGE
    # ════════════════════════════════════════════
    story.append(Spacer(1, 35*mm))
    story.append(Paragraph("AICL", cover_title_style))
    story.append(Paragraph(
        "Architecture Compilation<br/>with Explicable Compilation",
        ParagraphStyle('CoverTitle2', parent=cover_title_style, fontSize=24, leading=30)
    ))
    story.append(Spacer(1, 6*mm))
    story.append(hr())
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(
        "If the compiler cannot explain why it generated a line of code,<br/>"
        "it should not generate it.",
        ParagraphStyle('CoverThesis', parent=cover_subtitle_style, fontSize=13, leading=19,
                        textColor=ACCENT)
    ))
    story.append(Spacer(1, 15*mm))
    story.append(Paragraph("Version 0.4.0", cover_meta_style))
    story.append(Paragraph("Philippe-Antoine", cover_meta_style))
    story.append(Paragraph("June 2026", cover_meta_style))
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph("MIT License", cover_meta_style))

    story.append(PageBreak())

    # ════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ════════════════════════════════════════════
    toc = TableOfContents()
    toc.levelStyles = [toc_h1_style, toc_h2_style]
    story.append(Paragraph("Table of Contents", h1_style))
    story.append(toc)
    story.append(PageBreak())

    # ════════════════════════════════════════════
    # 1. ABSTRACT
    # ════════════════════════════════════════════
    story.append(Paragraph("1. Abstract", h1_style))
    story.append(p(
        "This paper presents AICL (Architecture Compilation Language), a specification-first "
        "programming system where risks, recoveries, and validations are mandatory syntactic "
        "elements, and every generated line of code carries full provenance. The central thesis "
        "of this work is the principle of <b>explicable compilation</b>: a compiler that cannot "
        "explain why it generated a line of code should not generate it."
    ))
    story.append(p(
        "Unlike conventional compilers that treat compilation as a pure translation from source "
        "to target, AICL treats compilation as a reasoning process where architecture, risks, "
        "recoveries, and validations all contribute to the generated code and are traceable back "
        "to their origin. The system enforces a deterministic compilation contract: the same input "
        "always produces the same output, with no probabilistic or AI-driven steps in the core "
        "compilation pipeline. AI assistance is available as an optional plugin, strictly separated "
        "from the deterministic compiler."
    ))
    story.append(p(
        "The language provides 27 reserved keywords across 10 progressive levels, a 9-stage "
        "compilation pipeline, 30+ deterministic behavior patterns, and a provenance tracker "
        "that records the reasoning path for every compilation decision. This paper describes "
        "the language design, compilation architecture, provenance system, and the philosophical "
        "foundation of explicable compilation."
    ))

    # ════════════════════════════════════════════
    # 2. THE PROBLEM
    # ════════════════════════════════════════════
    story.append(Paragraph("2. The Problem: Silent Compilers", h1_style))
    story.append(p(
        "Every production software system requires error handling, failure recovery, and "
        "validation. In every mainstream programming language, these concerns are optional "
        "afterthoughts. They are scattered across try/catch blocks, buried in documentation, "
        "or forgotten entirely. The gap between what architects intend to build and what "
        "developers actually build is where most production failures live."
    ))
    story.append(p(
        "But there is a deeper problem than the absence of risk management in source code. "
        "Modern compilers generate millions of lines of code without ever being able to answer "
        "a simple question: <b>why?</b> Why was this line generated? What architectural decision "
        "produced it? What risk does this recovery address? What validation does this test verify? "
        "No mainstream compiler can answer these questions. The code exists, but the reasoning "
        "behind it is lost the moment compilation finishes."
    ))
    story.append(p(
        "This loss of reasoning has practical consequences. When a production system fails at "
        "3:00 AM, the on-call engineer must reconstruct the intent behind code they did not write, "
        "based on error messages that reference code whose purpose is undocumented. Architecture "
        "documents describe risk scenarios and recovery strategies, but nothing enforces their "
        "implementation. Code reviews miss edge cases. Tests skip failure paths. The result: "
        "systems that work on the happy path and crumble on every other one."
    ))
    story.append(p(
        "The rise of AI-generated code has made this problem worse, not better. AI code generators "
        "produce code that works, sometimes, for some inputs, but they cannot tell you why they "
        "chose one implementation over another, whether they considered the edge cases your "
        "architecture document describes, or what risks they failed to address. The compiler has "
        "become a black box, and the black box is getting blacker."
    ))

    # ════════════════════════════════════════════
    # 3. THE THESIS
    # ════════════════════════════════════════════
    story.append(Paragraph("3. The Thesis: Explicable Compilation", h1_style))
    story.append(quote(
        "If the compiler cannot explain why it generated a line of code, "
        "it should not generate it."
    ))
    story.append(p(
        "This principle, which we call <b>explicable compilation</b>, is the central thesis "
        "of AICL. It is not a debugging feature or an after-the-fact documentation tool. It is "
        "a design constraint on the compiler itself: the compiler must be structured such that "
        "every output line has a traceable provenance chain back to the source specification."
    ))
    story.append(Paragraph("3.1 What Explicable Compilation Means", h2_style))
    story.append(p(
        "Explicable compilation means three things simultaneously. First, <b>provenance</b>: "
        "every generated line must be traceable to a specific source construct, a specific "
        "compilation decision, and a specific transformation step. Second, <b>determinism</b>: "
        "the compilation process must be fully deterministic so that the provenance chain is "
        "reproducible. The same input always produces the same output with the same provenance "
        "records. Third, <b>accountability</b>: if the compiler cannot produce a provenance "
        "chain for a generated line, it must fall back to an explicit sub-language syntax "
        "rather than guessing. The compiler would rather acknowledge "
        "its limitations than silently guess."
    ))
    story.append(Paragraph("3.2 What Explicable Compilation Does Not Mean", h2_style))
    story.append(p(
        "Explicable compilation does not mean that the compiler must generate human-readable "
        "explanations for every line of code as comments. It does not mean that the compiler "
        "must use AI to justify its decisions. And it does not mean that the generated code must "
        "be trivially simple so that it is easy to explain. Rather, it means that the compiler "
        "must maintain an internal audit trail that can be queried and inspected, and that this "
        "audit trail must be the primary artifact of compilation, not a secondary byproduct."
    ))
    story.append(p(
        "The distinction is important. A conventional compiler could, in theory, be modified to "
        "emit annotations about its optimization passes. But these annotations would be post-hoc "
        "rationalizations of decisions already made. In AICL, the provenance record is produced "
        "before the code is generated: the compiler first determines what it will generate and why, "
        "records this decision, and then generates the code. The provenance is not a commentary on "
        "the code; it is the reason for the code."
    ))
    story.append(Paragraph("3.3 The Provenance Principle", h2_style))
    story.append(p(
        "The provenance principle can be stated formally: for every line L in the generated output, "
        "there must exist a provenance record P such that P.source maps to a construct in the AICL "
        "input, P.resolution_path describes the sequence of compilation decisions that led to L, "
        "P.confidence quantifies the compiler's certainty in the match, and P.generated_code "
        "contains L. If no such P can be constructed, the compiler must not generate L; instead, "
        "it must use an explicit fallback mechanism that the programmer can inspect and override."
    ))
    story.append(p(
        "This principle has profound implications for compiler design. It means that the compiler "
        "cannot silently fill in code based on heuristics without recording those heuristics. It "
        "cannot optimize code in ways that are not traceable. And it cannot use probabilistic "
        "methods (including AI) in the core compilation path without violating the determinism "
        "requirement that makes provenance reproducible."
    ))

    # ════════════════════════════════════════════
    # 4. LANGUAGE DESIGN
    # ════════════════════════════════════════════
    story.append(Paragraph("4. Language Design", h1_style))
    story.append(p(
        "AICL is a specification-first language where the programmer describes what a system must "
        "achieve rather than how it achieves it. The language is organized in 10 progressive levels, "
        "where Level 1 (Architecture) is mandatory for all programs and higher levels add capabilities "
        "as needed. This design ensures that even the simplest AICL program carries the minimal "
        "architectural information needed for explicable compilation: a goal, a layer structure, "
        "and at least one validation criterion."
    ))

    story.append(Paragraph("4.1 Core Principles", h2_style))
    story.append(p(
        "Three principles govern the language design. <b>Architecture as program</b>: the "
        "architectural specification is the program, not a document about the program. Layers, "
        "entities, and behaviors are not documentation; they are compilation inputs that directly "
        "determine the structure of the generated code. <b>Risk as syntax</b>: risks and recoveries "
        "are not optional error-handling patterns; they are mandatory syntactic elements that the "
        "compiler enforces the way other compilers enforce type systems. <b>Validation as test</b>: "
        "validation sections are not aspirational statements; they are compiled into executable "
        "test code that verifies the system meets its specification."
    ))

    story.append(Paragraph("4.2 The Ten Language Levels", h2_style))
    level_data = [
        ['1', 'Architecture', 'Goal, Constraint, Risk, Recovery, Layer, Sublayer, Validation', 'Mandatory'],
        ['2', 'Entities', 'Entity + typed fields', 'Data models'],
        ['3', 'Behaviors', 'Behavior, Input, Output, Action', 'Entity operations'],
        ['4', 'Conditions', 'Condition, When, Then', 'Decision logic'],
        ['5', 'Events', 'Event, On, Action', 'Event-driven logic'],
        ['6', 'Concurrency', 'Parallel', 'Concurrent execution'],
        ['7', 'Optimization', 'Optimize, Priority', 'Performance targets'],
        ['8', 'Learning', 'Learn, Adapt, Based', 'ML integration'],
        ['9', 'Security', 'Security, Encrypt, Protect', 'Security directives'],
        ['10', 'Native Code', 'Native', 'Escape hatch'],
    ]
    story.append(make_table(
        ['Level', 'Feature', 'Keywords', 'Purpose'],
        level_data,
        col_widths=[28, 55, 220, 120]
    ))
    story.append(Paragraph("Table 1: AICL Language Levels", caption_style))

    story.append(Paragraph("4.3 Minimal Valid Program", h2_style))
    story.append(p(
        "The smallest meaningful AICL program requires only three constructs: a Goal that states "
        "what the system must achieve, a Layer that defines a structural component, and a Validation "
        "that specifies how to verify correctness. This minimal program is already richer than the "
        "equivalent hello-world in any mainstream language because it encodes intent, structure, and "
        "a test criterion in four lines:"
    ))
    story.append(code(
        "Goal:<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Hello World<br/>"
        "Layer:<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Core<br/>"
        "Validation:<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Output is produced"
    ))

    story.append(Paragraph("4.4 Risk and Recovery as Mandatory Constructs", h2_style))
    story.append(p(
        "In AICL, every Risk must have a paired Recovery. This is not a style guideline or a "
        "linting rule; it is a compile-time requirement enforced by the grammar. The compiler "
        "pairs risks with recoveries during the Risk Analysis stage (Stage 4) and synthesizes "
        "recovery logic during Recovery Synthesis (Stage 5). If a Risk has no Recovery, the "
        "compiler generates a generic fallback recovery and records a provenance entry indicating "
        "that the recovery was synthesized rather than specified."
    ))
    story.append(p(
        "This design ensures that production systems built with AICL cannot silently ignore failure "
        "modes. The architecture document that describes risks and recovery strategies is no longer "
        "a separate artifact that may or may not be implemented; it is the source code itself, and "
        "the compiler guarantees that every identified risk has corresponding recovery logic in the "
        "generated output."
    ))
    story.append(code(
        "Risk:<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Ball leaves play area<br/>"
        "Recovery:<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Clamp ball position to boundaries"
    ))
    story.append(p(
        "The compiler transforms this risk/recovery pair into executable code that clamps the ball "
        "position, and the provenance record traces this code back to the specific Risk and Recovery "
        "sections in the source. When a developer runs <font face='DejaVuSansMono' size='8.5'>aicl "
        "explain</font>, they can see exactly why the clamping code exists and what failure scenario "
        "it addresses."
    ))

    story.append(Paragraph("4.5 Validation as Compiled Tests", h2_style))
    story.append(p(
        "Validation sections in AICL are not comments about what should be tested. They are compiled "
        "into executable pytest suites during the Test Generation stage (Stage 7). The compiler uses "
        "keyword analysis to determine what each validation checks and generates appropriate test "
        "methods. For example, the validation 'Complete one playable match' generates a test that "
        "verifies the game loop executes successfully, while 'Maintain 60 FPS during gameplay' "
        "generates a performance test."
    ))
    story.append(p(
        "The provenance system tracks each generated test back to its source Validation section, "
        "creating a bidirectional link between specification and verification. This means that "
        "when a test fails, the developer can immediately identify which architectural requirement "
        "is not being met, rather than reverse-engineering the test's intent from its implementation."
    ))

    # ════════════════════════════════════════════
    # 5. COMPILATION PIPELINE
    # ════════════════════════════════════════════
    story.append(Paragraph("5. Compilation Pipeline", h1_style))
    story.append(p(
        "The AICL compiler transforms architectural specifications into executable source code "
        "through a 9-stage pipeline. Unlike conventional compilers that focus primarily on "
        "syntactic and semantic analysis followed by code generation, the AICL pipeline treats "
        "risk analysis, recovery synthesis, and provenance recording as first-class compilation "
        "stages. Each stage produces intermediate artifacts and provenance records that are "
        "carried forward through subsequent stages."
    ))

    pipeline_data = [
        ['1', 'Parsing', 'Source to AST with 17 node types'],
        ['2', 'Architecture Validation', 'Structural completeness (Goal, Layer, Validation present)'],
        ['3', 'Dependency Analysis', 'Layer dependency graph and execution order'],
        ['4', 'Risk Analysis', 'Risk/Recovery pairing (every Risk needs a Recovery)'],
        ['5', 'Recovery Synthesis', 'Recovery logic generation with provenance recording'],
        ['6', 'Code Generation', 'Python source with 30+ deterministic behavior patterns'],
        ['7', 'Test Generation', 'pytest suite from Validation sections'],
        ['8', 'Optimization', 'Apply Optimize/Priority hints'],
        ['9', 'Final Construction', 'Assemble main.py + test_main.py + architecture tree'],
    ]
    story.append(make_table(
        ['Stage', 'Name', 'Function'],
        pipeline_data,
        col_widths=[35, 110, 278]
    ))
    story.append(Paragraph("Table 2: The 9-Stage Compilation Pipeline", caption_style))

    story.append(Paragraph("5.1 Deterministic Behavior Compilation", h2_style))
    story.append(p(
        "The key innovation in the code generation stage is the Behavior Pattern Library: a set "
        "of 30+ deterministic patterns that map action descriptions to concrete, executable code. "
        "When the compiler encounters a Behavior section, it analyzes the action description using "
        "keyword-based scoring with word-boundary matching. If a pattern matches with confidence "
        "above 0.3, the compiler uses that pattern's code template. If no pattern matches, the "
        "compiler falls back to the sub-language parser, which handles explicit action "
        "specifications such as 'assign', 'clamp', 'check', 'send', 'return', and 'log'."
    ))
    story.append(p(
        "This approach guarantees deterministic compilation: the same AICL source always produces "
        "the same Python output, regardless of the execution environment, random seed, or any "
        "other non-deterministic factor. The compiler does not guess. It either finds a pattern "
        "that matches with documented confidence, uses an explicit sub-language specification, or "
        "produces a structured fallback skeleton with full provenance indicating that human review "
        "is needed."
    ))

    pattern_data = [
        ['Movement', 'MOVE, MOVE_BALL, REFLECT_VELOCITY, CLAMP_POSITION'],
        ['Creation', 'CREATE, INIT_LAYER, CREATE_WINDOW'],
        ['Communication', 'BROADCAST, SEND_MESSAGE'],
        ['Update', 'UPDATE, INCREMENT_SCORE, UPDATE_STATE, ADD_TO_COLLECTION'],
        ['Display', 'DISPLAY, RENDER_FRAME, HIGHLIGHT'],
        ['Validation', 'VALIDATE, CHECK_COLLISION'],
        ['Networking', 'CONNECT, RECONNECT, DISCONNECT'],
        ['Persistence', 'STORE, LOAD'],
        ['Security', 'ENCRYPT_DATA, PROTECT_ACCESS'],
        ['Sync', 'SYNC_STATE, BUFFER_INPUT'],
        ['Game', 'END_GAME, APPLY_PHYSICS'],
        ['Adaptation', 'ADAPT_QUALITY, SUGGEST, QUEUE_MESSAGE'],
    ]
    story.append(make_table(
        ['Category', 'Patterns'],
        pattern_data,
        col_widths=[80, 343]
    ))
    story.append(Paragraph("Table 3: Behavior Pattern Categories", caption_style))

    story.append(Paragraph("5.2 Architecture Template Mapping", h2_style))
    story.append(p(
        "The compiler uses the Goal section to select an application structure template. The "
        "ArchitectureTemplateMapper maps goal keywords to one of four structural patterns: "
        "game_loop (init-update-render-loop, for games and simulations), event_driven "
        "(connect-listen-handle-respond, for servers and chat systems), pipeline "
        "(ingest-process-output, for data processing), and crud (list-create-read-update-delete, "
        "for data management). This template determines the main application loop structure, "
        "the method signatures, and the execution model of the generated code."
    ))
    story.append(p(
        "The template selection is deterministic and provenance-tracked. The compiler records "
        "which template was selected, why (based on which keywords in the Goal section), and "
        "with what confidence. This means that when a developer questions why their chat "
        "application uses an event-driven architecture, the provenance record can answer: "
        "because the Goal contained 'chat' and 'server' keywords, which matched the "
        "event_driven template with confidence 0.87."
    ))

    story.append(Paragraph("5.3 Sub-Language Parser", h2_style))
    story.append(p(
        "When no behavior pattern matches with sufficient confidence, the sub-language parser "
        "provides an explicit syntax for specifying actions. The sub-language supports eight "
        "statement types: assign (with operators +=, -=, =, *=), clamp (between min and max), "
        "check (with comparison operators), send (message to destination), return, call "
        "(method invocation), log (message), and raise (exception). This sub-language ensures "
        "that even when the pattern library does not cover a specific action, the programmer "
        "can still express it deterministically without resorting to native code."
    ))
    story.append(code(
        "Behavior MovePaddle<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Input: Player direction string<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;Action: assign paddle_position += direction * speed<br/>"
        "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
        "clamp paddle_position between 0 and screen_width"
    ))

    # ════════════════════════════════════════════
    # 6. PROVENANCE SYSTEM
    # ════════════════════════════════════════════
    story.append(Paragraph("6. Provenance System", h1_style))
    story.append(p(
        "The provenance system is the mechanism through which AICL implements explicable "
        "compilation. It records a trace of every compilation decision, from the initial parsing "
        "of source constructs to the final generation of code and tests. This trace is not "
        "generated after compilation as a debugging aid; it is produced during compilation as "
        "an integral part of the compilation process."
    ))

    story.append(Paragraph("6.1 Provenance Types", h2_style))
    story.append(p(
        "Every compilation decision is classified into one of twelve provenance types, each "
        "indicating the nature of the decision and the reasoning path that was followed. These "
        "types form a taxonomy of compilation reasoning that enables systematic analysis of "
        "compiler behavior."
    ))
    prov_data = [
        ['PATTERN_MATCH', 'A behavior pattern matched with sufficient confidence'],
        ['SUB_LANGUAGE', 'Explicit sub-language syntax was used'],
        ['FALLBACK', 'No pattern matched; structured skeleton generated'],
        ['ARCHITECTURE_TEMPLATE', 'Goal mapped to application structure'],
        ['DIRECT_MAPPING', 'Keyword directly mapped to code'],
        ['RECOVERY_SYNTHESIS', 'Recovery code synthesized from Risk/Recovery pair'],
        ['VALIDATION_SYNTHESIS', 'Test code generated from Validation section'],
        ['CONDITION_SYNTHESIS', 'Condition handler generated from When/Then'],
        ['EVENT_SYNTHESIS', 'Event handler generated from On/Action'],
        ['ENTITY_GENERATION', 'Dataclass generated from Entity definition'],
        ['LAYER_INITIALIZATION', 'Component initialization from Layer definition'],
        ['HELPER_METHOD', 'Utility method generated to support other code'],
    ]
    story.append(make_table(
        ['Type', 'Meaning'],
        prov_data,
        col_widths=[130, 293]
    ))
    story.append(Paragraph("Table 4: Provenance Types", caption_style))

    story.append(Paragraph("6.2 The Provenance Record", h2_style))
    story.append(p(
        "Each provenance record contains five fields: <b>source</b>, which identifies the AICL "
        "construct that triggered the compilation decision; <b>resolution_path</b>, which describes "
        "the sequence of steps the compiler took to arrive at the decision; <b>generated_code</b>, "
        "which contains the actual code that was produced; <b>confidence</b>, which quantifies the "
        "compiler's certainty in the match (for pattern-based decisions) or is set to 1.0 (for "
        "deterministic mappings); and <b>pattern_name</b>, which identifies the specific pattern "
        "or mechanism that was used."
    ))
    story.append(p(
        "The <font face='DejaVuSansMono' size='8.5'>aicl explain</font> command traverses these "
        "provenance records and produces a human-readable trace of the compilation process. When "
        "invoked with the <font face='DejaVuSansMono' size='8.5'>--behavior</font> flag, it "
        "focuses on a specific behavior and shows the pattern matching process in detail. When "
        "invoked with <font face='DejaVuSansMono' size='8.5'>--provenance</font>, it produces "
        "a full provenance report covering every compilation decision."
    ))

    story.append(Paragraph("6.3 The Explainability Contract", h2_style))
    story.append(p(
        "The provenance system enforces an explainability contract: every line of generated code "
        "must have at least one provenance record. If the compiler generates code without a "
        "corresponding provenance record, this is a compiler bug, not an acceptable gap. This "
        "contract ensures that the <font face='DejaVuSansMono' size='8.5'>aicl explain</font> "
        "command can always provide a complete accounting of the compilation process."
    ))
    story.append(p(
        "The explainability contract also serves as a constraint on future compiler development. "
        "Any new optimization pass, code generation strategy, or transformation must be accompanied "
        "by provenance recording. This prevents the compiler from growing features that would "
        "violate the explicable compilation principle."
    ))

    # ════════════════════════════════════════════
    # 7. DETERMINISTIC COMPILATION CONTRACT
    # ════════════════════════════════════════════
    story.append(Paragraph("7. Deterministic Compilation Contract", h1_style))
    story.append(p(
        "AICL enforces a strict deterministic compilation contract: the same AICL source code, "
        "compiled with the same compiler version and target language, must always produce "
        "identical output. This is not merely a desirable property; it is a fundamental design "
        "requirement that enables the provenance system to provide meaningful and reproducible "
        "explanations."
    ))
    story.append(p(
        "The determinism contract has several implications. First, the compiler cannot use random "
        "number generation, current timestamps, or any other non-deterministic input in the "
        "compilation path. Second, the compiler cannot use AI models in the core pipeline, since "
        "AI model outputs are inherently probabilistic. Third, the behavior pattern matching "
        "algorithm must be deterministic: given the same input, it must always select the same "
        "pattern with the same confidence score."
    ))
    story.append(p(
        "AI assistance is available in AICL through the <font face='DejaVuSansMono' size='8.5'>"
        "--ai-fill</font> flag, but this mode is explicitly separate from the core compiler. When "
        "AI fill is used, the provenance records clearly indicate which code was generated by AI "
        "and which was generated deterministically. This separation ensures that developers always "
        "know which parts of their codebase have deterministic provenance and which parts rely on "
        "probabilistic generation."
    ))

    # ════════════════════════════════════════════
    # 8. FORMAL GRAMMAR
    # ════════════════════════════════════════════
    story.append(Paragraph("8. Formal Grammar", h1_style))
    story.append(p(
        "AICL has a formal BNF grammar with 27 reserved keywords. The grammar is line-based, "
        "supporting two formats for keyword-value pairs: inline (Keyword: Value on the same line) "
        "and block (Keyword: on one line, indented Value on the next). This dual format allows "
        "both concise single-line specifications and multi-line descriptions, making the language "
        "readable for both simple and complex programs."
    ))
    story.append(p(
        "The complete BNF grammar is provided in the specification file at "
        "<font face='DejaVuSansMono' size='8.5'>spec/grammar.md</font>. The grammar defines "
        "productions for all 10 language levels, including nested structures such as Entity "
        "fields within Entity blocks, Behavior sub-sections (Input, Output, Action), and "
        "indented Security action blocks. The grammar enforces the Risk/Recovery pairing "
        "requirement at the structural level."
    ))

    story.append(Paragraph("8.1 Type System", h2_style))
    story.append(p(
        "AICL provides 11 built-in type names that can be used in Entity field declarations "
        "and Behavior input/output specifications: string, integer, float, boolean, datetime, "
        "list, dict, set, any, void, and bytes. The type system is intentionally simple: it "
        "provides enough expressiveness for architectural specification without introducing the "
        "complexity of a full type inference system. Types are used for documentation and code "
        "generation purposes; they do not carry runtime type-checking semantics in the current "
        "implementation."
    ))

    story.append(Paragraph("8.2 Keyword Reference", h2_style))
    keyword_data = [
        ['Goal', '1', 'Define system objective'],
        ['Constraint', '1', 'Specify system constraints'],
        ['Risk', '1', 'Identify potential failure'],
        ['Recovery', '1', 'Define failure response'],
        ['Layer', '1', 'Define architectural layer'],
        ['Sublayer', '1', 'Define sub-component'],
        ['Validation', '1', 'Specify verification criterion'],
        ['Entity', '2', 'Define data model'],
        ['Behavior', '3', 'Define operation'],
        ['Input', '3', 'Define behavior input'],
        ['Output', '3', 'Define behavior output'],
        ['Action', '3', 'Define behavior action'],
        ['Condition', '4', 'Define conditional logic'],
        ['When', '4', 'Condition trigger'],
        ['Then', '4', 'Condition response'],
        ['Event', '5', 'Define event handler'],
        ['On', '5', 'Event trigger'],
        ['Parallel', '6', 'Define concurrent execution'],
        ['Optimize', '7', 'Define optimization target'],
        ['Priority', '7', 'Set optimization priority'],
        ['Learn', '8', 'Define learning objective'],
        ['Adapt', '8', 'Define adaptation rule'],
        ['Based', '8', 'Adaptation basis'],
        ['Security', '9', 'Define security directive'],
        ['Encrypt', '9', 'Encryption action'],
        ['Protect', '9', 'Protection action'],
        ['Native', '10', 'Embed native code'],
    ]
    story.append(make_table(
        ['Keyword', 'Level', 'Purpose'],
        keyword_data,
        col_widths=[65, 35, 323]
    ))
    story.append(Paragraph("Table 5: Complete Keyword Reference", caption_style))

    # ════════════════════════════════════════════
    # 9. INTERMEDIATE REPRESENTATION
    # ════════════════════════════════════════════
    story.append(Paragraph("9. Intermediate Representation", h1_style))
    story.append(p(
        "Between the AST and the code generation stage, the compiler constructs an Architecture "
        "Tree: a hierarchical intermediate representation that organizes the flat list of AST "
        "sections into a tree structure reflecting the system's architectural decomposition. The "
        "root node represents the System as a whole, with child nodes for each Layer, Entity, "
        "and Behavior. Risks, recoveries, validations, and constraints are attached to the "
        "appropriate nodes in the tree."
    ))
    story.append(p(
        "The Architecture Tree serves several purposes. It provides a structural basis for the "
        "dependency analysis stage, which determines the order in which layers should be "
        "initialized and executed. It enables risk distribution, which attempts to associate each "
        "risk with the architectural layer most likely to be affected. And it provides a "
        "visualization of the system architecture that can be output as a text file using the "
        "<font face='DejaVuSansMono' size='8.5'>aicl tree</font> command."
    ))
    story.append(p(
        "The tree visualization uses symbolic annotations to indicate the presence of risks, "
        "recoveries, validations, and constraints at each level. The symbol set includes warning "
        "markers for risks, recovery markers for recovery strategies, check markers for "
        "validations, and constraint markers for architectural constraints. This provides a "
        "quick visual summary of where risk management and verification are concentrated in "
        "the architecture."
    ))

    # ════════════════════════════════════════════
    # 10. COMPARATIVE ANALYSIS
    # ════════════════════════════════════════════
    story.append(Paragraph("10. Comparative Analysis", h1_style))
    story.append(p(
        "AICL occupies a unique position in the landscape of programming languages, domain-specific "
        "languages, and code generation systems. This section compares AICL with related approaches "
        "along the dimensions that matter most for explicable compilation."
    ))

    comp_data = [
        ['Risk/Recovery mandatory', 'No', 'No', 'No', 'Yes'],
        ['Validation compiles to tests', 'No', 'No', 'No', 'Yes'],
        ['Full compilation provenance', 'No', 'No', 'No', 'Yes'],
        ['Deterministic compilation', 'Yes', 'No', 'Yes', 'Yes'],
        ['Architecture as program', 'No', 'Partial', 'No', 'Yes'],
        ['AI-free core pipeline', 'Yes', 'No', 'Yes', 'Yes'],
        ['Specification-first syntax', 'No', 'No', 'Yes', 'Yes'],
    ]
    story.append(make_table(
        ['Feature', 'Mainstream', 'AI Code Gen', 'Traditional DSL', 'AICL'],
        comp_data,
        col_widths=[130, 72, 72, 72, 72]
    ))
    story.append(Paragraph("Table 6: Comparative Analysis", caption_style))

    story.append(Paragraph("10.1 Mainstream Languages", h2_style))
    story.append(p(
        "Languages like Python, Rust, Go, and C++ treat error handling as an optional practice. "
        "Even Rust, which enforces error handling through its Result type, does not require "
        "developers to identify risks before writing code or to pair each risk with a recovery "
        "strategy. None of these languages provide compilation provenance. The compiler generates "
        "code but cannot explain why specific code was generated or trace generated lines back "
        "to architectural decisions."
    ))

    story.append(Paragraph("10.2 AI Code Generation", h2_style))
    story.append(p(
        "AI code generators like GitHub Copilot, ChatGPT, and Cursor produce code that is often "
        "functional but never explainable in the AICL sense. These systems use probabilistic models "
        "to generate code, meaning the same prompt may produce different code on different runs. "
        "There is no provenance chain linking generated code to the architectural intent that "
        "prompted it. The code works until it does not, and when it fails, there is no trace of "
        "the reasoning that produced it. AICL's deterministic compilation contract and provenance "
        "system are direct responses to this problem."
    ))

    story.append(Paragraph("10.3 Traditional DSLs and ADLs", h2_style))
    story.append(p(
        "Domain-specific languages and architecture description languages share AICL's "
        "specification-first philosophy. However, traditional DSLs focus on generating "
        "configuration, boilerplate, or specialized code within a narrow domain. They do not "
        "treat risks as mandatory constructs, do not compile validations into tests, and do not "
        "provide compilation provenance. Architecture description languages like ArchiMate and "
        "SysML describe system structure but do not compile into executable code with error "
        "handling. AICL bridges the gap between architectural specification and executable "
        "code while maintaining the provenance chain that makes the bridge traceable."
    ))

    # ════════════════════════════════════════════
    # 11. IMPLEMENTATION STATUS
    # ════════════════════════════════════════════
    story.append(Paragraph("11. Implementation Status", h1_style))
    story.append(p(
        "The current implementation (v0.4.0) includes a complete parser for all 10 language levels, "
        "a 9-stage compilation pipeline that generates Python code, a behavior pattern library with "
        "30+ deterministic patterns, a sub-language parser for explicit action specifications, a "
        "provenance tracker that records every compilation decision, and a CLI with five commands: "
        "compile, parse, tree, check, and explain. The test suite contains 63 tests, all passing. "
        "Four example programs of increasing complexity compile to zero-TODO Python code."
    ))
    story.append(p(
        "Several components are currently minimal or stubbed and are targets for future development. "
        "The dependency analysis stage currently returns layers in source order rather than computing "
        "a true dependency graph. The optimization stage counts remaining TODOs but does not apply "
        "optimization transformations. The risk distribution algorithm in the Architecture Tree "
        "computes keyword-based scores but does not actually redistribute risks to layers. And the "
        "target language backend currently only supports Python; Rust, JavaScript, and Go backends "
        "are planned for v1.0."
    ))
    story.append(p(
        "The validation methods generated by the compiler use keyword-based heuristics to determine "
        "what each validation checks. While this approach works for the current example programs, "
        "more sophisticated validation code generation is needed for complex real-world scenarios. "
        "Similarly, helper methods like collision detection and check detection currently return "
        "default values rather than performing real computations. These are areas where the "
        "deterministic pattern library needs to expand."
    ))

    # ════════════════════════════════════════════
    # 12. FUTURE DIRECTIONS
    # ════════════════════════════════════════════
    story.append(Paragraph("12. Future Directions", h1_style))

    story.append(Paragraph("12.1 Memory Management", h2_style))
    story.append(p(
        "A critical area for future development is memory management. The goal is to provide an "
        "ultra-simple ownership model that is more effective than existing systems like Zig's "
        "manual memory management. The challenge is to express ownership and lifetime semantics "
        "within AICL's architectural specification paradigm, where the programmer describes intent "
        "rather than implementation. A promising direction is to derive ownership rules from the "
        "Layer and Entity structure: layers own their entities, behaviors borrow entities from their "
        "layers, and the compiler enforces borrow checking at the architectural level before "
        "generating code. This would give AICL programs memory safety guarantees without requiring "
        "programmers to think about pointers, allocators, or lifetimes directly."
    ))

    story.append(Paragraph("12.2 Multi-File Programs", h2_style))
    story.append(p(
        "The current implementation supports only single-file AICL programs. Multi-file support "
        "(planned for v0.5) will introduce import and module mechanisms that allow architectural "
        "specifications to be decomposed across multiple files. This raises questions about "
        "provenance across file boundaries: when a behavior in one file uses an entity defined in "
        "another, the provenance chain must span both files. The design must ensure that explicable "
        "compilation is not compromised by modularization."
    ))

    story.append(Paragraph("12.3 Multi-Language Targets", h2_style))
    story.append(p(
        "The compiler currently generates only Python code. Multi-language targets (Rust, "
        "JavaScript, Go) are planned for v1.0. Each target language raises unique challenges "
        "for explicable compilation. Rust's ownership model, JavaScript's event loop, and Go's "
        "goroutine model each require different code generation strategies, and the provenance "
        "system must track which language-specific decisions were made and why. The explicable "
        "compilation principle provides a natural framework for this: the provenance record must "
        "indicate not just what code was generated, but why it was generated differently for "
        "Rust than for Python."
    ))

    story.append(Paragraph("12.4 Self-Healing Runtime", h2_style))
    story.append(p(
        "The v2.0 milestone envisions a self-healing runtime that can automatically execute "
        "recovery strategies when risks materialize at runtime. This would transform AICL's "
        "Risk/Recovery pairs from compile-time specifications into runtime instrumentation, "
        "where the generated code includes monitoring hooks that detect risk conditions and "
        "trigger the corresponding recovery code. The provenance system would extend to "
        "cover runtime events, creating a complete trace from architectural risk identification "
        "through code generation to runtime recovery execution."
    ))

    story.append(Paragraph("12.5 Provenance Visualization", h2_style))
    story.append(p(
        "The current provenance output is text-based, accessed through the <font "
        "face='DejaVuSansMono' size='8.5'>aicl explain</font> command. Future work will "
        "develop interactive visualization tools that allow developers to explore the provenance "
        "graph, trace compilation decisions visually, and navigate between source specifications "
        "and generated code. This would make the explicable compilation principle accessible to "
        "developers who are not compiler experts."
    ))

    # ════════════════════════════════════════════
    # 13. CONCLUSION
    # ════════════════════════════════════════════
    story.append(Paragraph("13. Conclusion", h1_style))
    story.append(p(
        "AICL presents a new approach to the relationship between architecture and code. Rather "
        "than treating architecture as documentation that informs code, AICL treats architecture "
        "as the program itself, and compiles it into executable code with mandatory risk management, "
        "automatic test generation, and full compilation provenance."
    ))
    story.append(p(
        "The central contribution of this work is the principle of explicable compilation: the "
        "idea that a compiler should be able to explain why it generated every line of code it "
        "produces, and that if it cannot explain, it should not generate. This principle is "
        "implemented through a provenance system that records every compilation decision, a "
        "deterministic compilation contract that makes provenance reproducible, and a language "
        "design that makes risks, recoveries, and validations mandatory rather than optional."
    ))
    story.append(p(
        "The real test of any language is not its white paper but whether someone else can take "
        "it and build an application without its creator. AICL is not yet at that point. The "
        "pattern library needs to expand, the generated code needs to be more sophisticated, and "
        "the memory management system needs to be designed and implemented. But the core "
        "idea—that compilers should be able to explain themselves, and that this explainability "
        "should be enforced by design rather than added as an afterthought—is one that deserves "
        "serious exploration."
    ))
    story.append(p(
        "In a world where AI code generators produce code without accountability, where production "
        "systems fail at 3:00 AM because risks were documented but not compiled, and where the "
        "gap between architectural intent and implemented code grows wider every year, the "
        "principle of explicable compilation offers a different direction. Not more code generation, "
        "but more accountable code generation. Not faster compilation, but more transparent "
        "compilation. Not AI that writes code, but compilers that can explain the code they write."
    ))

    # ════════════════════════════════════════════
    # 14. REFERENCES
    # ════════════════════════════════════════════
    story.append(Paragraph("14. References", h1_style))
    refs = [
        "[1] AICL Project Repository. https://github.com/AFKmoney/AICL",
        "[2] AICL Formal Grammar Specification. spec/grammar.md",
        "[3] AICL Compilation Provenance Implementation. src/aicl/provenance.py",
        "[4] AICL Behavior Pattern Library. src/aicl/patterns.py",
        "[5] AICL Test Suite. tests/test_aicl.py",
        "[6] Garlan, D. and Shaw, M. Software Architecture: Perspectives on an Emerging Discipline. Prentice Hall, 1996.",
        "[7] Clements, P. et al. Documenting Software Architectures: Views and Beyond. Addison-Wesley, 2010.",
        "[8] Mernik, M. et al. 'Domain-Specific Languages: A Systematic Mapping Study.' Information and Software Technology, 2022.",
        "[9] Van Deursen, A. et al. 'Domain-Specific Languages: An Annotated Bibliography.' ACM SIGPLAN Notices, 2000.",
        "[10] Zig Programming Language. https://ziglang.org/",
    ]
    for ref in refs:
        story.append(Paragraph(ref, ParagraphStyle(
            'Ref', parent=body_style, fontSize=9, leading=13,
            leftIndent=8*mm, spaceBefore=1*mm, spaceAfter=1.5*mm,
        )))

    # ════════════════════════════════════════════
    # BUILD
    # ════════════════════════════════════════════
    doc.build(story, onFirstPage=cover_page_template, onLaterPages=page_header_footer)
    print(f"White paper generated: {output_path}")
    return output_path


if __name__ == '__main__':
    build_whitepaper()
