"""
AICL Autonomous Compilation System — Self-Writing, Self-Validating Code

The central thesis: a compiler that cannot explain why it generated a line
should not generate it. This module extends that thesis to its logical
conclusion: a compiler that can diagnose its own failures, fix its own
specifications, learn new patterns, and validate its own output — all
while preserving the No-Orphan Property.

The Autonomous Compilation Loop:
    SPEC → COMPILE → VERIFY → TEST → DIAGNOSE → FIX → RECOMPILE
                     ↑                                      │
                     └──────────────────────────────────────┘

Every iteration of the loop preserves the provenance chain. Every fix
is recorded. Every learned pattern is tracked. The loop converges when:
    1. Spec verification passes (completeness, coherence, satisfaction)
    2. Audit coverage = 1.0 (no orphans)
    3. All generated tests pass
    4. No fallback compilations remain
    5. Improvement score converges (delta < threshold)

New ProvenanceTypes added by this module:
    - AI_GENERATION: Code generated by AI-assisted fallback
    - SELF_HEALING: Code fixed by autonomous diagnosis
    - PATTERN_LEARNED: New pattern learned from unmatched actions
    - SPEC_EVOLVED: Specification modified by autonomous evolution

Usage:
    aicl evolve <source.aicl> [--max-iterations 10] [--no-ai]
    aicl evolve <source.aicl> --watch  # continuous mode
"""

import os
import re
import sys
import json
import time
import hashlib
import subprocess
import tempfile
import shutil
import traceback
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple, Set, Any
from enum import Enum

from .provenance import ProvenanceType


class LoopState(Enum):
    """State of the autonomous compilation loop."""
    INITIALIZING = "initializing"
    COMPILING = "compiling"
    VERIFYING = "verifying"
    TESTING = "testing"
    DIAGNOSING = "diagnosing"
    FIXING = "fixing"
    LEARNING = "learning"
    CONVERGED = "converged"
    FAILED = "failed"
    TIMED_OUT = "timed_out"


@dataclass
class LoopIteration:
    """Record of a single loop iteration."""
    iteration: int
    state_entered: LoopState
    timestamp_start: float
    state_exited: LoopState = LoopState.INITIALIZING
    timestamp_end: float = 0.0
    spec_changes: List[str] = field(default_factory=list)
    patterns_learned: List[str] = field(default_factory=list)
    tests_passed: int = 0
    tests_failed: int = 0
    tests_total: int = 0
    audit_coverage: float = 0.0
    fallback_count: int = 0
    provenance_records_added: int = 0
    errors: List[str] = field(default_factory=list)
    fixes_applied: List[str] = field(default_factory=list)

    @property
    def duration(self) -> float:
        return self.timestamp_end - self.timestamp_start

    @property
    def success(self) -> bool:
        return (
            self.tests_failed == 0
            and self.tests_total > 0
            and self.audit_coverage >= 1.0
            and self.fallback_count == 0
        )


@dataclass
class AutonomousResult:
    """Final result of an autonomous compilation session."""
    converged: bool
    iterations: List[LoopIteration]
    total_duration: float
    final_audit_coverage: float
    final_test_pass_rate: float
    patterns_learned: List[str]
    spec_evolution: List[str]
    convergence_iteration: Optional[int] = None
    proof_valid: bool = False

    @property
    def summary(self) -> str:
        lines = [
            f"Converged: {self.converged}",
            f"Iterations: {len(self.iterations)}",
            f"Duration: {self.total_duration:.2f}s",
            f"Audit Coverage: {self.final_audit_coverage:.1%}",
            f"Test Pass Rate: {self.final_test_pass_rate:.1%}",
            f"Patterns Learned: {len(self.patterns_learned)}",
            f"Spec Changes: {len(self.spec_evolution)}",
            f"Proof Valid: {self.proof_valid}",
        ]
        if self.convergence_iteration is not None:
            lines.append(f"Converged at iteration: {self.convergence_iteration}")
        return "\n".join(lines)


class TestRunner:
    """Execute generated tests and analyze failures."""

    def __init__(self, timeout: int = 30):
        self.timeout = timeout
        self.last_results: Dict[str, Any] = {}

    def run_tests(self, output_dir: str) -> Tuple[int, int, int, List[Dict]]:
        """
        Run pytest on the generated test file.
        Returns (passed, failed, total, failure_details).
        """
        test_file = os.path.join(output_dir, "test_main.py")
        if not os.path.exists(test_file):
            return 0, 0, 0, [{"error": "No test file found"}]

        # Try to find pytest - check venv first, then system
        pytest_path = shutil.which("pytest")
        python_path = sys.executable

        try:
            cmd = [python_path, "-m", "pytest", test_file, "-v", "--tb=short", "--no-header"]
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self.timeout,
                cwd=output_dir,
            )
        except subprocess.TimeoutExpired:
            return 0, 0, 0, [{"error": f"Test execution timed out after {self.timeout}s"}]
        except Exception as e:
            return 0, 0, 0, [{"error": f"Test execution failed: {str(e)}"}]

        # Parse pytest output
        passed, failed, total = 0, 0, 0
        failure_details = []

        for line in result.stdout.split("\n"):
            line = line.strip()
            # Match: "test_main.py::test_validation_1 PASSED"
            if " PASSED" in line:
                passed += 1
                total += 1
            elif " FAILED" in line:
                failed += 1
                total += 1
                test_name = line.split("::")[-1].split()[0] if "::" in line else "unknown"
                failure_details.append({"test": test_name, "raw": line})

        # Also check the summary line: "X passed, Y failed"
        for line in result.stdout.split("\n"):
            m = re.match(r"(\d+) passed", line)
            if m:
                passed = int(m.group(1))
            m = re.match(r".*?(\d+) failed", line)
            if m:
                failed = int(m.group(1))
            m = re.match(r".*?(\d+) warning", line)
            # total = passed + failed

        if total == 0:
            total = passed + failed

        self.last_results = {
            "passed": passed,
            "failed": failed,
            "total": total,
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }

        return passed, failed, total, failure_details

    def analyze_failure(self, test_name: str, output_dir: str) -> Dict[str, Any]:
        """Analyze a specific test failure and return diagnostic info."""
        test_file = os.path.join(output_dir, "test_main.py")
        main_file = os.path.join(output_dir, "main.py")

        diagnosis = {
            "test_name": test_name,
            "missing_imports": [],
            "missing_methods": [],
            "attribute_errors": [],
            "type_errors": [],
            "assertion_failures": [],
            "suggested_fix": None,
        }

        stdout = self.last_results.get("stdout", "")
        stderr = self.last_results.get("stderr", "")

        full_output = stdout + "\n" + stderr

        # Pattern-based diagnosis
        if "ModuleNotFoundError" in full_output or "ImportError" in full_output:
            for m in re.finditer(r"No module named '(\w+)'", full_output):
                diagnosis["missing_imports"].append(m.group(1))
            diagnosis["suggested_fix"] = "add_missing_imports"

        if "AttributeError" in full_output:
            for m in re.finditer(r"'(\w+)' object has no attribute '(\w+)'", full_output):
                diagnosis["attribute_errors"].append({
                    "class": m.group(1),
                    "attribute": m.group(2),
                })
            diagnosis["suggested_fix"] = "add_missing_attributes"

        if "TypeError" in full_output:
            diagnosis["type_errors"].append(full_output[:500])
            diagnosis["suggested_fix"] = "fix_type_signatures"

        if "AssertionError" in full_output or "assert" in full_output:
            diagnosis["assertion_failures"].append(test_name)
            diagnosis["suggested_fix"] = "fix_validation_logic"

        if "NameError" in full_output:
            for m in re.finditer(r"name '(\w+)' is not defined", full_output):
                diagnosis["missing_methods"].append(m.group(1))
            diagnosis["suggested_fix"] = "add_missing_definitions"

        # Check if main.py exists and has content
        if os.path.exists(main_file):
            with open(main_file) as f:
                main_content = f.read()
            diagnosis["main_file_lines"] = len(main_content.split("\n"))
        else:
            diagnosis["main_file_lines"] = 0
            diagnosis["suggested_fix"] = "regenerate_main"

        return diagnosis


class PatternLearner:
    """
    Learn new behavior patterns from unmatched action descriptions.

    When the deterministic pattern matcher falls back (no match found),
    the PatternLearner analyzes the unmatched description and creates
    a candidate pattern that can be used in future compilations.
    """

    def __init__(self):
        self.learned_patterns: Dict[str, Dict] = {}
        self.unmatched_descriptions: List[str] = []

    def record_unmatched(self, behavior_name: str, description: str):
        """Record an unmatched action description for learning."""
        self.unmatched_descriptions.append(f"{behavior_name}: {description}")

    def learn_from_description(self, behavior_name: str, description: str) -> Optional[Dict]:
        """
        Analyze an unmatched action description and generate a candidate pattern.
        Returns a pattern dict or None if no pattern can be inferred.
        """
        desc_lower = description.lower().strip()

        # Extract verbs and objects from the description
        verb = self._extract_verb(desc_lower)
        obj = self._extract_object(desc_lower)

        if not verb or not obj:
            return None

        # Classify the pattern based on verb-object analysis
        pattern = {
            "name": f"LEARNED_{behavior_name.upper()}",
            "behavior": behavior_name,
            "verb": verb,
            "object": obj,
            "category": self._classify_category(verb, obj),
            "keywords": self._extract_keywords(desc_lower),
            "description": description,
            "template": self._generate_template(verb, obj, behavior_name),
            "confidence": 0.7,  # Learned patterns start at 0.7 (below deterministic 0.95)
            "learned_at": time.time(),
        }

        self.learned_patterns[behavior_name] = pattern
        return pattern

    def _extract_verb(self, description: str) -> str:
        """Extract the primary verb from an action description."""
        action_verbs = [
            "create", "delete", "update", "modify", "set", "change",
            "add", "remove", "append", "push", "pop", "insert",
            "validate", "verify", "check", "assert", "confirm",
            "send", "receive", "transmit", "broadcast", "dispatch",
            "calculate", "compute", "evaluate", "process", "analyze",
            "convert", "transform", "translate", "map",
            "store", "save", "load", "fetch", "retrieve",
            "encrypt", "decrypt", "sign", "verify",
            "connect", "disconnect", "reconnect",
            "start", "stop", "pause", "resume", "cancel",
            "lock", "unlock", "freeze", "unfreeze",
            "approve", "reject", "accept", "deny",
            "compile", "generate", "build", "produce",
            "notify", "alert", "signal", "emit",
            "apply", "execute", "run", "invoke",
            "debit", "credit", "transfer", "exchange",
            "suspend", "escalate", "flag",
            "log", "record", "audit",
        ]
        words = description.split()
        for word in words:
            if word in action_verbs:
                return word
        # Fallback: first word
        return words[0] if words else ""

    def _extract_object(self, description: str) -> str:
        """Extract the primary object from an action description."""
        # Look for entity-like nouns
        financial_objects = [
            "account", "transaction", "loan", "payment", "balance",
            "customer", "card", "deposit", "withdrawal", "transfer",
            "currency", "rate", "fraud", "alert", "audit",
        ]
        general_objects = [
            "message", "data", "state", "position", "score",
            "user", "player", "game", "board", "piece",
            "file", "record", "entry", "item", "element",
            "connection", "session", "request", "response",
        ]
        all_objects = financial_objects + general_objects

        words = description.split()
        for word in words:
            if word in all_objects:
                return word

        # Fallback: noun after the verb
        for i, word in enumerate(words):
            if i > 0 and word not in ["to", "from", "with", "and", "or", "the", "a", "an", "in", "on", "at", "for"]:
                return word

        return words[-1] if words else "data"

    def _classify_category(self, verb: str, obj: str) -> str:
        """Classify the action into a pattern category."""
        category_map = {
            "create": "CREATION", "delete": "DELETION", "add": "UPDATE",
            "remove": "DELETION", "update": "UPDATE", "modify": "UPDATE",
            "set": "UPDATE", "change": "UPDATE",
            "validate": "VALIDATE", "verify": "VALIDATE", "check": "VALIDATE",
            "send": "ROUTE", "receive": "ROUTE", "transmit": "BROADCAST",
            "broadcast": "BROADCAST", "dispatch": "ROUTE",
            "calculate": "COMPUTE", "compute": "COMPUTE", "evaluate": "COMPUTE",
            "convert": "TRANSFORM", "transform": "TRANSFORM",
            "store": "STORE", "save": "STORE", "load": "LOAD",
            "fetch": "LOAD", "retrieve": "LOAD",
            "encrypt": "ENCRYPT", "decrypt": "ENCRYPT",
            "connect": "CONNECT", "disconnect": "DISCONNECT",
            "notify": "NOTIFY", "alert": "NOTIFY",
            "debit": "FINANCIAL", "credit": "FINANCIAL",
            "transfer": "FINANCIAL", "exchange": "FINANCIAL",
            "suspend": "SECURITY", "lock": "SECURITY", "freeze": "SECURITY",
            "log": "AUDIT", "record": "AUDIT", "audit": "AUDIT",
        }
        return category_map.get(verb, "GENERAL")

    def _extract_keywords(self, description: str) -> List[str]:
        """Extract searchable keywords from a description."""
        stop_words = {"to", "from", "with", "and", "or", "the", "a", "an",
                      "in", "on", "at", "for", "is", "are", "was", "were",
                      "be", "been", "being", "have", "has", "had", "do",
                      "does", "did", "will", "would", "could", "should",
                      "may", "might", "must", "shall", "can", "need",
                      "it", "its", "if", "then", "else", "when", "where",
                      "which", "who", "whom", "this", "that", "these", "those"}
        words = re.findall(r'\b\w+\b', description.lower())
        return [w for w in words if w not in stop_words and len(w) > 2]

    def _generate_template(self, verb: str, obj: str, behavior_name: str) -> str:
        """Generate a code template for a learned pattern."""
        templates = {
            "CREATION": f'''        """Behavior: {behavior_name}"""
        instance = {obj.title().replace('_', '')}()
        self._logger.info(f"Created {{}}: {{instance}}")
        return instance''',
            "UPDATE": f'''        """Behavior: {behavior_name}"""
        {obj}.{verb}_value = new_value
        self._logger.info(f"{verb} {obj}: {{{obj}.{verb}_value}}")''',
            "VALIDATE": f'''        """Behavior: {behavior_name}"""
        result = self._validate_{obj}({obj})
        if not result:
            self._logger.warning(f"Validation failed for {{}}")
        return result''',
            "STORE": f'''        """Behavior: {behavior_name}"""
        self._storage["{obj}"] = {obj}
        self._logger.info(f"Stored {obj}")''',
            "LOAD": f'''        """Behavior: {behavior_name}"""
        data = self._storage.get("{obj}")
        self._logger.info(f"Loaded {obj}: {{data}}")
        return data''',
            "FINANCIAL": f'''        """Behavior: {behavior_name}"""
        # {verb} {obj} with full audit trail
        self._logger.info(f"{verb} {obj}")
        record = self._create_audit_entry("{verb}", "{obj}")
        self._audit_trail.append(record)
        return record''',
            "NOTIFY": f'''        """Behavior: {behavior_name}"""
        for recipient in self._recipients:
            self._notify(recipient, "{obj}")
        self._logger.info(f"Notified about {{obj}}")''',
            "AUDIT": f'''        """Behavior: {behavior_name}"""
        entry = self._create_audit_entry("{verb}", "{obj}")
        self._audit_trail.append(entry)
        self._logger.info(f"Audit entry created: {{entry}}")
        return entry''',
            "SECURITY": f'''        """Behavior: {behavior_name}"""
        {obj}.status = "suspended"
        self._logger.info(f"{verb} {obj} for security review")
        self._notify_security("{verb}", {obj})''',
            "ROUTE": f'''        """Behavior: {behavior_name}"""
        self._send_to(destination, {obj})
        self._logger.info(f"{verb} {obj} to {{destination}}")''',
            "BROADCAST": f'''        """Behavior: {behavior_name}"""
        for recipient in self._recipients:
            self._send_to(recipient, {obj})
        self._logger.info(f"Broadcast {obj}")''',
        }

        category = self._classify_category(verb, obj)
        return templates.get(category, f'''        """Behavior: {behavior_name}"""
        # {verb} {obj}
        self._logger.info(f"{verb} {obj}")
        pass''')

    def get_learned_pattern(self, behavior_name: str) -> Optional[Dict]:
        """Get a learned pattern for a behavior."""
        return self.learned_patterns.get(behavior_name)

    def export_patterns(self) -> List[Dict]:
        """Export all learned patterns for serialization."""
        return [
            {**p, "learned_at": p["learned_at"]}
            for p in self.learned_patterns.values()
        ]


class SpecEvolver:
    """
    Evolve/fix AICL specifications based on diagnostic information.

    The SpecEvolver takes verification failures, test failures, and
    audit gaps as input, and produces specification modifications
    that address the root cause — not the symptom.

    Every modification is recorded in the provenance chain.
    """

    def __init__(self):
        self.evolution_log: List[Dict] = []

    def evolve_from_verification(self, source: str, report: Dict) -> Tuple[str, List[str]]:
        """
        Modify the AICL source based on a verification report.
        Returns (modified_source, list_of_changes).
        """
        changes = []
        lines = source.split("\n")

        for check in report.get("checks", []):
            if check.get("status") == "FAIL":
                change = self._fix_verification_failure(lines, check)
                if change:
                    changes.append(change)
                    self.evolution_log.append({
                        "type": "verification_fix",
                        "check": check,
                        "change": change,
                        "timestamp": time.time(),
                    })

        return "\n".join(lines), changes

    def evolve_from_test_failure(self, source: str, diagnosis: Dict) -> Tuple[str, List[str]]:
        """
        Modify the AICL source based on a test failure diagnosis.
        Returns (modified_source, list_of_changes).
        """
        changes = []
        lines = source.split("\n")

        fix_type = diagnosis.get("suggested_fix")

        if fix_type == "add_missing_imports":
            change = self._fix_missing_imports(lines, diagnosis)
            if change:
                changes.append(change)

        elif fix_type == "add_missing_attributes":
            change = self._fix_missing_attributes(lines, diagnosis)
            if change:
                changes.append(change)

        elif fix_type == "fix_validation_logic":
            change = self._fix_validation_logic(lines, diagnosis)
            if change:
                changes.append(change)

        elif fix_type == "add_missing_definitions":
            change = self._fix_missing_definitions(lines, diagnosis)
            if change:
                changes.append(change)

        elif fix_type == "fix_type_signatures":
            change = self._fix_type_signatures(lines, diagnosis)
            if change:
                changes.append(change)

        for change in changes:
            self.evolution_log.append({
                "type": "test_failure_fix",
                "diagnosis": diagnosis,
                "change": change,
                "timestamp": time.time(),
            })

        return "\n".join(lines), changes

    def evolve_from_audit_gap(self, source: str, audit_report: Dict) -> Tuple[str, List[str]]:
        """
        Modify the AICL source to address audit coverage gaps.
        Returns (modified_source, list_of_changes).
        """
        changes = []
        lines = source.split("\n")

        orphan_artifacts = audit_report.get("orphan_artifacts", [])
        coverage = audit_report.get("audit_coverage", 0.0)

        if coverage < 1.0:
            # Add more specific validations to cover gaps
            change = self._add_coverage_validations(lines, orphan_artifacts, coverage)
            if change:
                changes.append(change)
                self.evolution_log.append({
                    "type": "audit_gap_fix",
                    "coverage": coverage,
                    "change": change,
                    "timestamp": time.time(),
                })

        return "\n".join(lines), changes

    def _fix_verification_failure(self, lines: List[str], check: Dict) -> Optional[str]:
        """Fix a specific verification failure."""
        check_name = check.get("name", "")
        message = check.get("message", "")

        if "risk_recovery_pairing" in check_name:
            # Risk without recovery — add a generic recovery
            last_risk_idx = -1
            for i, line in enumerate(lines):
                if line.strip().startswith("Risk:"):
                    last_risk_idx = i

            if last_risk_idx >= 0:
                # Find the next blank line after the risk
                insert_idx = last_risk_idx + 1
                while insert_idx < len(lines) and lines[insert_idx].strip():
                    insert_idx += 1

                risk_text = lines[last_risk_idx].replace("Risk:", "").strip()
                lines.insert(insert_idx, f"Recovery:")
                lines.insert(insert_idx + 1, f"Handle {risk_text.lower()} gracefully")
                return f"Added recovery for risk: {risk_text}"

        elif "entity_present" in check_name or "behavior_present" in check_name:
            # Missing entity or behavior — can't auto-fix, return None
            return None

        elif "action" in check_name:
            # Behavior without action — add a generic action
            for i, line in enumerate(lines):
                if line.strip().startswith("Behavior "):
                    # Check if there's no Action: section
                    has_action = False
                    for j in range(i + 1, min(i + 10, len(lines))):
                        if "Action:" in lines[j]:
                            has_action = True
                            break
                        if lines[j].strip() and not lines[j].startswith(" ") and not lines[j].startswith("\t"):
                            break
                    if not has_action:
                        behavior_name = line.replace("Behavior", "").strip()
                        lines.insert(i + 1, "")
                        lines.insert(i + 2, "Action:")
                        lines.insert(i + 3, f"    execute {behavior_name.lower()}")
                        return f"Added action for behavior: {behavior_name}"

        return None

    def _fix_missing_imports(self, lines: List[str], diagnosis: Dict) -> Optional[str]:
        """Add missing imports — note: this affects generated code, not AICL source."""
        # For AICL source, missing imports usually means the Native section needs updating
        for missing in diagnosis.get("missing_imports", []):
            # Check if there's a Native section
            for i, line in enumerate(lines):
                if line.strip().startswith("Native:"):
                    return f"Missing import '{missing}' should be added to Native section"

        return None

    def _fix_missing_attributes(self, lines: List[str], diagnosis: Dict) -> Optional[str]:
        """Add missing entity fields based on attribute errors."""
        fixes = []
        for error in diagnosis.get("attribute_errors", []):
            cls_name = error.get("class", "")
            attr_name = error.get("attribute", "")

            # Find the entity definition and add the missing field
            for i, line in enumerate(lines):
                if line.strip().startswith(f"Entity {cls_name}"):
                    # Add the missing field
                    j = i + 1
                    while j < len(lines) and (lines[j].startswith("    ") or lines[j].startswith("\t")):
                        j += 1
                    lines.insert(j, f"    {attr_name}: any")
                    fixes.append(f"Added field '{attr_name}' to Entity {cls_name}")
                    break

        return "; ".join(fixes) if fixes else None

    def _fix_validation_logic(self, lines: List[str], diagnosis: Dict) -> Optional[str]:
        """Make validations more specific and testable."""
        # Make vague validations more testable
        for i, line in enumerate(lines):
            if line.strip().startswith("Validation:"):
                validation_text = line.replace("Validation:", "").strip()
                # Check if the validation is too vague
                vague_patterns = ["works correctly", "functions properly", "operates as expected"]
                for pattern in vague_patterns:
                    if pattern in validation_text.lower():
                        lines[i] = f"Validation: {validation_text.replace(pattern, 'produces expected output and returns success')}"
                        return f"Made validation more specific: {validation_text[:50]}..."

        return None

    def _fix_missing_definitions(self, lines: List[str], diagnosis: Dict) -> Optional[str]:
        """Add missing entity or behavior definitions."""
        fixes = []
        for name in diagnosis.get("missing_methods", []):
            # Check if it might be a missing entity
            entity_name = name.title().replace("_", "")
            # Add a minimal entity if it makes sense
            has_entity = any(f"Entity {entity_name}" in line for line in lines)
            if not has_entity and len(name) > 3:
                # Add at the end of entities section
                last_entity = -1
                for i, line in enumerate(lines):
                    if line.strip().startswith("Entity "):
                        last_entity = i
                if last_entity >= 0:
                    # Find end of last entity
                    j = last_entity + 1
                    while j < len(lines) and (lines[j].startswith("    ") or lines[j].startswith("\t")):
                        j += 1
                    lines.insert(j, f"\nEntity {entity_name}")
                    lines.insert(j + 1, f"    id: string")
                    lines.insert(j + 2, f"    name: string")
                    fixes.append(f"Added Entity {entity_name}")

        return "; ".join(fixes) if fixes else None

    def _fix_type_signatures(self, lines: List[str], diagnosis: Dict) -> Optional[str]:
        """Fix type signature mismatches in behaviors."""
        # Often caused by Behavior Input sections using raw types instead of Entity names
        for error in diagnosis.get("type_errors", []):
            # This is usually a generated code issue, not a spec issue
            pass
        return None

    def _add_coverage_validations(self, lines: List[str], orphans: List, coverage: float) -> Optional[str]:
        """Add validations to improve audit coverage."""
        # Find the last Validation section
        last_validation = -1
        for i, line in enumerate(lines):
            if line.strip().startswith("Validation:"):
                last_validation = i

        # Add a general validation for coverage
        if last_validation >= 0:
            lines.insert(last_validation + 1, "Validation:")
            lines.insert(last_validation + 2, "All generated code artifacts have traceable provenance")
            return f"Added coverage validation (was {coverage:.1%})"

        return None


class LoopController:
    """
    Manage the autonomous compilation loop with convergence detection.

    Convergence criteria:
        1. All spec verifications pass
        2. Audit coverage = 1.0
        3. All generated tests pass
        4. No fallback compilations remain
        5. Improvement score delta < threshold (0.01)
    """

    def __init__(self, max_iterations: int = 10, convergence_threshold: float = 0.01):
        self.max_iterations = max_iterations
        self.convergence_threshold = convergence_threshold
        self.iterations: List[LoopIteration] = []
        self.history: List[Dict] = []

    @property
    def current_iteration(self) -> int:
        return len(self.iterations)

    @property
    def should_continue(self) -> bool:
        """Whether the loop should continue iterating."""
        if self.current_iteration >= self.max_iterations:
            return False
        if self.is_converged:
            return False
        return True

    @property
    def is_converged(self) -> bool:
        """Whether the loop has converged."""
        if len(self.history) < 2:
            return False

        current = self.history[-1]
        previous = self.history[-2]

        # All metrics must be at maximum
        if current.get("audit_coverage", 0) < 1.0:
            return False
        if current.get("test_pass_rate", 0) < 1.0:
            return False
        if current.get("fallback_count", 1) > 0:
            return False
        if not current.get("spec_verified", False):
            return False

        # Improvement must be below threshold
        delta = abs(
            current.get("score", 0) - previous.get("score", 0)
        )
        return delta < self.convergence_threshold

    @property
    def convergence_iteration(self) -> Optional[int]:
        """The iteration at which convergence was reached."""
        for i, h in enumerate(self.history):
            if (
                h.get("audit_coverage", 0) >= 1.0
                and h.get("test_pass_rate", 0) >= 1.0
                and h.get("fallback_count", 1) == 0
                and h.get("spec_verified", False)
            ):
                return i + 1
        return None

    def record_iteration(self, iteration: LoopIteration):
        """Record a completed iteration."""
        self.iterations.append(iteration)
        self.history.append({
            "iteration": iteration.iteration,
            "audit_coverage": iteration.audit_coverage,
            "test_pass_rate": iteration.tests_passed / max(iteration.tests_total, 1),
            "fallback_count": iteration.fallback_count,
            "spec_verified": iteration.tests_failed == 0 and iteration.audit_coverage >= 1.0,
            "score": self._compute_score(iteration),
            "patterns_learned": len(iteration.patterns_learned),
            "fixes_applied": len(iteration.fixes_applied),
        })

    def _compute_score(self, iteration: LoopIteration) -> float:
        """Compute a composite score for an iteration."""
        coverage_score = iteration.audit_coverage
        test_score = iteration.tests_passed / max(iteration.tests_total, 1)
        fallback_penalty = iteration.fallback_count * 0.05
        return max(0, (coverage_score + test_score) / 2 - fallback_penalty)

    def get_progress(self) -> Dict[str, Any]:
        """Get current progress information."""
        if not self.history:
            return {"status": "starting", "iteration": 0}

        current = self.history[-1]
        return {
            "status": "converged" if self.is_converged else "iterating",
            "iteration": self.current_iteration,
            "max_iterations": self.max_iterations,
            "score": current.get("score", 0),
            "audit_coverage": current.get("audit_coverage", 0),
            "test_pass_rate": current.get("test_pass_rate", 0),
            "fallback_count": current.get("fallback_count", 0),
            "total_patterns_learned": sum(h.get("patterns_learned", 0) for h in self.history),
            "total_fixes_applied": sum(h.get("fixes_applied", 0) for h in self.history),
        }


class AutonomousCompiler:
    """
    The self-writing, self-validating compilation engine.

    Orchestrates the full autonomous loop:
        SPEC → COMPILE → VERIFY → TEST → DIAGNOSE → FIX → RECOMPILE

    Every step preserves the No-Orphan Property. Every fix is recorded
    in the provenance chain. The loop converges when all criteria are met.

    Usage:
        compiler = AutonomousCompiler(max_iterations=10)
        result = compiler.evolve("banking.aicl")
        print(result.summary)
    """

    def __init__(self, max_iterations: int = 10, target_language: str = "python",
                 test_timeout: int = 30, convergence_threshold: float = 0.01):
        self.max_iterations = max_iterations
        self.target_language = target_language
        self.test_runner = TestRunner(timeout=test_timeout)
        self.pattern_learner = PatternLearner()
        self.spec_evolver = SpecEvolver()
        self.loop_controller = LoopController(
            max_iterations=max_iterations,
            convergence_threshold=convergence_threshold,
        )
        self._provenance_log: List[Dict] = []

    def evolve(self, source_path: str, output_dir: Optional[str] = None) -> AutonomousResult:
        """
        Run the autonomous compilation loop on an AICL source file.

        Args:
            source_path: Path to the .aicl source file
            output_dir: Output directory (defaults to temp dir)

        Returns:
            AutonomousResult with convergence details
        """
        start_time = time.time()

        # Read source
        with open(source_path) as f:
            source = f.read()

        original_source = source

        if output_dir is None:
            output_dir = tempfile.mkdtemp(prefix="aicl_evolve_")

        # Import compiler here to avoid circular imports
        from . import Compiler, Parser

        spec_verified = False

        while self.loop_controller.should_continue:
            iteration_num = self.loop_controller.current_iteration + 1
            iter_start = time.time()

            iteration = LoopIteration(
                iteration=iteration_num,
                state_entered=LoopState.COMPILING,
                timestamp_start=iter_start,
            )

            # === STEP 1: COMPILE ===
            iteration.state_entered = LoopState.COMPILING
            try:
                compiler = Compiler(target_language=self.target_language)
                result = compiler.compile_to_file(source, output_dir, source_path=source_path)

                if not result.success:
                    iteration.errors.append(f"Compilation failed: {'; '.join(result.errors)}")
                    iteration.state_exited = LoopState.FAILED
                    iteration.timestamp_end = time.time()
                    self.loop_controller.record_iteration(iteration)
                    continue

                # Parse for verification step
                try:
                    parsed = Parser().parse(source)
                except Exception:
                    parsed = None

                # Count fallbacks from provenance
                fallback_count = 0
                if hasattr(compiler, '_provenance') and compiler._provenance:
                    for rec in compiler._provenance.records:
                        if rec.source_type == ProvenanceType.FALLBACK:
                            fallback_count += 1
                            # Record for pattern learning
                            self.pattern_learner.record_unmatched(
                                rec.source_text[:50] if rec.source_text else "unknown",
                                rec.generated_code[:200] if rec.generated_code else ""
                            )

                iteration.fallback_count = fallback_count

                # Get audit coverage
                if hasattr(compiler, '_provenance') and compiler._provenance:
                    audit = compiler._provenance.compute_audit_coverage()
                    iteration.audit_coverage = audit.get("audit_coverage", 0.0)

            except Exception as e:
                iteration.errors.append(f"Compilation exception: {str(e)}")
                iteration.state_exited = LoopState.FAILED
                iteration.timestamp_end = time.time()
                self.loop_controller.record_iteration(iteration)
                continue

            # === STEP 2: VERIFY SPEC ===
            iteration.state_entered = LoopState.VERIFYING
            try:
                from .spec_verify import SpecificationVerifier
                if parsed is not None:
                    verifier = SpecificationVerifier(parsed)
                    report = verifier.verify(source_name=source_path)

                    spec_verified = all(
                        c.get("status") != "FAIL"
                        for c in report.get("checks", [])
                    )

                    if not spec_verified:
                        # Auto-fix spec verification failures
                        source, changes = self.spec_evolver.evolve_from_verification(source, report)
                        iteration.spec_changes.extend(changes)
                        iteration.fixes_applied.extend(changes)
                else:
                    spec_verified = False

            except Exception as e:
                iteration.errors.append(f"Verification exception: {str(e)}")
                spec_verified = False

            # === STEP 3: RUN TESTS ===
            iteration.state_entered = LoopState.TESTING
            try:
                passed, failed, total, failures = self.test_runner.run_tests(output_dir)
                iteration.tests_passed = passed
                iteration.tests_failed = failed
                iteration.tests_total = total

                if failed > 0:
                    # === STEP 4: DIAGNOSE FAILURES ===
                    iteration.state_entered = LoopState.DIAGNOSING
                    for failure in failures:
                        test_name = failure.get("test", "unknown")
                        diagnosis = self.test_runner.analyze_failure(test_name, output_dir)

                        # === STEP 5: FIX ===
                        iteration.state_entered = LoopState.FIXING
                        source, changes = self.spec_evolver.evolve_from_test_failure(source, diagnosis)
                        iteration.fixes_applied.extend(changes)

            except Exception as e:
                iteration.errors.append(f"Test execution exception: {str(e)}")
                iteration.tests_total = 1
                iteration.tests_failed = 1

            # === STEP 6: LEARN PATTERNS ===
            if iteration.fallback_count > 0:
                iteration.state_entered = LoopState.LEARNING
                for unmatched in self.pattern_learner.unmatched_descriptions:
                    parts = unmatched.split(": ", 1)
                    if len(parts) == 2:
                        pattern = self.pattern_learner.learn_from_description(parts[0], parts[1])
                        if pattern:
                            iteration.patterns_learned.append(pattern["name"])

                # Clear after learning
                self.pattern_learner.unmatched_descriptions.clear()

            # === STEP 7: CHECK AUDIT COVERAGE ===
            if iteration.audit_coverage < 1.0:
                iteration.state_entered = LoopState.FIXING
                source, changes = self.spec_evolver.evolve_from_audit_gap(
                    source,
                    {
                        "audit_coverage": iteration.audit_coverage,
                        "orphan_artifacts": [],
                    }
                )
                iteration.fixes_applied.extend(changes)

            # Record iteration
            iteration.state_exited = (
                LoopState.CONVERGED if iteration.success else LoopState.DIAGNOSING
            )
            iteration.timestamp_end = time.time()
            self.loop_controller.record_iteration(iteration)

            # Record provenance for this iteration
            self._provenance_log.append({
                "iteration": iteration_num,
                "duration": iteration.duration,
                "audit_coverage": iteration.audit_coverage,
                "tests_passed": iteration.tests_passed,
                "tests_failed": iteration.tests_failed,
                "fallback_count": iteration.fallback_count,
                "patterns_learned": iteration.patterns_learned,
                "fixes_applied": iteration.fixes_applied,
                "spec_changes": iteration.spec_changes,
            })

        # === FINAL: Verify proof ===
        proof_valid = False
        proof_path = os.path.join(output_dir, "main.aicl-proof")
        if os.path.exists(proof_path):
            try:
                from .provenance import ProofOfOrigin
                proof = ProofOfOrigin.from_file(proof_path)
                valid, checks = proof.verify()
                proof_valid = valid
            except Exception:
                proof_valid = False

        # Compute final metrics
        total_duration = time.time() - start_time
        final_history = self.loop_controller.history
        final_coverage = final_history[-1].get("audit_coverage", 0) if final_history else 0
        final_pass_rate = final_history[-1].get("test_pass_rate", 0) if final_history else 0

        # If source was modified, write it back
        if source != original_source:
            evolved_path = source_path.replace(".aicl", ".evolved.aicl")
            with open(evolved_path, "w") as f:
                f.write(source)

        return AutonomousResult(
            converged=self.loop_controller.is_converged,
            iterations=self.loop_controller.iterations,
            total_duration=total_duration,
            final_audit_coverage=final_coverage,
            final_test_pass_rate=final_pass_rate,
            patterns_learned=[
                p["name"] for p in self.pattern_learner.learned_patterns.values()
            ],
            spec_evolution=[
                entry["change"] for entry in self.spec_evolver.evolution_log
            ],
            convergence_iteration=self.loop_controller.convergence_iteration,
            proof_valid=proof_valid,
        )


def format_evolve_report(result: AutonomousResult) -> str:
    """Format an AutonomousResult into a readable report."""
    lines = [
        "=" * 70,
        "AICL AUTONOMOUS COMPILATION REPORT",
        "=" * 70,
        "",
        f"  Converged:       {result.converged}",
        f"  Total Duration:  {result.total_duration:.2f}s",
        f"  Iterations:      {len(result.iterations)}",
        f"  Audit Coverage:  {result.final_audit_coverage:.1%}",
        f"  Test Pass Rate:  {result.final_test_pass_rate:.1%}",
        f"  Proof Valid:     {result.proof_valid}",
        "",
    ]

    if result.convergence_iteration is not None:
        lines.append(f"  Converged at:    Iteration {result.convergence_iteration}")
    else:
        lines.append(f"  Converged at:    N/A (did not converge)")

    lines.append("")

    # Patterns learned
    if result.patterns_learned:
        lines.append("PATTERNS LEARNED:")
        for p in result.patterns_learned:
            lines.append(f"  - {p}")
        lines.append("")

    # Spec evolution
    if result.spec_evolution:
        lines.append("SPECIFICATION EVOLUTION:")
        for change in result.spec_evolution:
            lines.append(f"  - {change}")
        lines.append("")

    # Iteration details
    lines.append("ITERATION DETAILS:")
    lines.append("-" * 70)
    for it in result.iterations:
        status = "✓ CONVERGED" if it.success else "→ ITERATING"
        lines.append(
            f"  [{it.iteration}] {status} "
            f"coverage={it.audit_coverage:.1%} "
            f"tests={it.tests_passed}/{it.tests_total} "
            f"fallbacks={it.fallback_count} "
            f"fixes={len(it.fixes_applied)} "
            f"patterns={len(it.patterns_learned)} "
            f"({it.duration:.2f}s)"
        )
        if it.errors:
            for err in it.errors[:3]:
                lines.append(f"         ⚠ {err[:80]}")
    lines.append("-" * 70)
    lines.append("")

    return "\n".join(lines)
